version: '3'

services:
  app:
    build: .
#    command: bash -c "alembic upgrade head && uvicorn main:app --reload --host 0.0.0.0 --port 8080"
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgresql://simplemeet:583Wgj2j3SWC@52.69.156.49:5432/simplemeetstaging
